### ISSUE TITLE
Provide additional information on collections

### ISSUE THREAD

**Issue by otbe** [contentful-labs/cf-graphql#12]
Hi there,

I wonder if its possible to add a meta section to collection queries (like relay connection) to fetch additional information like the total amount of entries. What do you think about it? Would be useful for paging :)

Thanks!

**Comment by jelz** [comment]
I've already investigated this topic and have some ideas. But it won't be a part of v0.4. I'll keep you posted.

**Comment by jelz** [comment]
Moved to v0.6.

**Comment by KevCJones** [comment]
+1 ...well i wish i had seen this yesterday. 

Do you have any sort of expected timeline for v0.6? Its fine if the extra collection info comes in later... i can probably survive with the limit of 1000 until then and just tally the results etc.

**Comment by jelz** [comment]
Released in v0.5.

Please refer https://github.com/contentful-labs/cf-graphql#querying
