### ISSUE TITLE
Endpoint can not be used quick and dirty from a different origin

### ISSUE THREAD

**Issue by stefanjudis** [contentful-labs/cf-graphql#16]
👋  I just played around with the demo and was not able to use the `/graphql` endpoint due to CORS issues. Especially for quick development using the `demo` folder we might want to set proper headers to not set road blocks for beginners.

I can provide a PR tomorrow, if desired. :)

**Comment by jelz** [comment]
@stefanjudis please provide a PR if you've got time.
