### ISSUE TITLE
Make queryFields accessible.

### ISSUE THREAD

**Issue by davidsims9t** [contentful-labs/cf-graphql#21]
Hello,

I'm working on constructing a GraphQL API and I'm integrating different services together into my GraphQL schema. One of those services is contentful. I was wondering if you have any plans for exposing the queryFields function in ./schema.js that way I can combine my queries into my root query.

Thanks,
David

**Comment by jelz** [comment]
@davidsims9t I've just released version 0.4.3. It exposes method(s) you've mentioned: https://github.com/contentful-labs/cf-graphql/blob/master/src/index.js#L12-L14

Could you please update to this version and let me know if it solves your problem?

**Comment by davidsims9t** [comment]
@jelz that's perfect. Thank you!
