### ISSUE TITLE
Consider adding the v1.0 roadmap to the wiki

### ISSUE THREAD

**Issue by ads1018** [contentful-labs/cf-graphql#27]
I'm evaluating GraphQL supported content management systems and I'm very interested in using Contentful in the near term. Obviously, I'm reluctant to use it until the disclaimers are removed and version 1.0 is released. Is there a roadmap for the 1.0 release that the team would be willing to share?

Thanks!

**Comment by jelz** [comment]
Thanks for including Contentful on your list. I'll check with the Product Management team here at Contentful and get back to you soon.

**Comment by jelz** [comment]
Sorry for keeping you waiting so long. The decision is we won't be working full time on the solution in Q3. We're going to evaluate again in the beginning of Q4. Usage and public reception of `cf-graphql` will be important factor.

We'll have a release of v0.5 this week. It'll be fixing multiple issues, introducing new functionalities and improving documentation.

Please remember this library is released under the MIT license and the code cannot be closed.
