### ISSUE TITLE
Locale isn't passed down from top level query to nested referece field resolving requests

### ISSUE THREAD

**Issue by ptMuta** [contentful-labs/cf-graphql#29]
Type: Bug

Description: 
When loading nested `Entry`-values the [`load`-function](https://github.com/contentful-labs/cf-graphql/blob/master/src/entry-loader.js#L27) does not pass on the original locale from the top level query to reference resolving request when resolving references nested deeper than a single level.

Reproduction:
* Create a content model with reference fields containing reference fields with localizable fields
* Query said model values with non-default locale:
```
{
  menus(q: "locale=fi") {
    title
    items {
      ... on MenuItem {
        title
        url
        page {
          title
          slug
        }
      }
    }
  }
}
```

Should return:
```
{
  ...
    "menus": [
      {
        "title": "Main Menu",
        "items": [
          {
            "title": "Etusivu",
            "url": null,
            "page": {
              "title": "Uutiset",
              "slug": "news"
            }
          },
          {
            "title": "Yhteystiedot",
            "url": null,
            "page": {
              "title": "Tietoa Meistä",
              "slug": "about"
            }
          },
        ]
      }
    ],
  ...
}
```

Instead returns:
```
{
  ...
    "menus": [
      {
        "title": "Main Menu",
        "items": [
          {
            "title": "Etusivu",
            "url": null,
            "page": {
              "title": "News",
              "slug": "news"
            }
          },
          {
            "title": "Yhteystiedot",
            "url": null,
            "page": {
              "title": "About us",
              "slug": "about"
            }
          }
        ]
      }
    ],
  ...
}
```

I'll try to whip up a patch but it'll take a while to get to know to the codebase. If anyone has a good hint or straight out fix, lemme now.

**Comment by ptMuta** [comment]
Workaround for the issue it to create locale specific middelware instances:
```javascript
const client = cfGraphql.createClient({ spaceId, cdaToken, cmaToken, locale });
const contentTypes = await client.getContentTypes();
const spaceGraph = await cfGraphql.prepareSpaceGraph(contentTypes);
const names = spaceGraph.map(ct => ct.names.type).join(', ');
const schema = await cfGraphql.createSchema(spaceGraph);
const middleware = graphqlHTTP(cfGraphql.helpers.expressGraphqlExtension(client, schema, {
    version: true,
    timeline: true,
    detailedErrors: false
}));
```

**Comment by jelz** [comment]
cf-graphql is intended to be used with a single locale at a time. Making it multi-locale would be a bigger project.

README of v0.5 explains is more detail the approach we currently use.

**Comment by sandgraham** [comment]
Hi, I was curious if there were any plans to support multi-locale queries at some point. It would be immensely useful for a project I am working on.

Thanks!

**Comment by bapjiws** [comment]
The same here. It would be extremely useful to have this support so that the locale could be used at query time.
