### ISSUE TITLE
How to properly mock cf-graphql?

### ISSUE THREAD

**Issue by creaux** [contentful-labs/cf-graphql#30]
I just wondering how to mock cf-graphql. I see that's it bit more difficult that it looked like and I see that just using graphql-tools its not easily possible as graphql schema is taken remotely I guess. 

What I need to achieve here is basically when I will be in mocked mode (offline) to be able still develop. So basically don't change a lot from source code.

Any suggestions how to do so?

**Comment by CodeAmend** [comment]
Please. I am curious as well.

**Comment by aperkaz** [comment]
Hello, I am also very interested on this. Thanks :slightly_smiling_face:

**Comment by creaux** [comment]
Original solution seems to sufficient using `graphql-tools` http://dev.apollodata.com/tools/graphql-tools/mocking.html. What will be missing is `schema` to generate it use just use https://github.com/graphcool/get-graphql-schema (as @aperkaz found) and point it to your graphql running instance. With storybook seems this https://github.com/abhiaiyer91/apollo-storybook-decorator to ease the job.
