### ISSUE TITLE
How to make work cf-graphql behind proxy?

### ISSUE THREAD

**Issue by creaux** [contentful-labs/cf-graphql#32]
Hello, whats the best way how to make work cf-graphql behind proxy?

```
There is an error in GraphQL: FetchError: request to https://api.contentful.com/spaces/blablabla/content_types?limit=1000 failed, reason: connect EPERM 1.2.3.4:443 - Local (5.6.7.8:52812)
```

**Comment by karna41317** [comment]
@creaux Did u make it work behind proxy ?.  I had the same issue.  I even tried with [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) but it did not work

**Comment by creaux** [comment]
@karna41317 you have to use system wide proxy.
