### ISSUE TITLE
Pagination with cf-graphql

### ISSUE THREAD

**Issue by richyrb00** [contentful-labs/cf-graphql#33]
with a normal graphql setup you can use the likes of (first:3) to only pull through the first 3 results in a query..

when using cf-graphql this isn't possible through the normal way...

can anyone advise on this?

**Comment by alcar** [comment]
I'm not sure if this is the most "correct" solution or more of a workaround, but I'll tell you how I dealt with that.
In `src/entry-loader.js`, the query function is defined as:

```js
function query (ctId, q) {
    const params = Object.assign({
      limit: 100,
      skip: 0,
      include: INCLUDE_DEPTH,
      content_type: ctId
    }, qs.parse(q || ''));

    return http.get('/entries', params).then(prime);
}
```

If you take a look at the second parameter of `Object.assign`, you'll notice that it parses the `q` parameter from the `query` function. Therefore, you can pass parameters using that `q`.

For example, I have a Content Type named `tutorial` and I want to fetch the titles of the "first" 3 tutorials (I don't know how they're actually sorted). I would do something like:
```graphql
query {
  tutorials(q: "limit=3") {
    title
}
```

For pagination, you could use:
```graphql
query {
  tutorials(q: "limit=3&skip=3") {
    title
}
```

Again, I'm not sure if this is the right way to do it, but I hope it works for you until someone from Contentful help you out :smiley:

**Comment by richyrb00** [comment]
@alcar that works perfectly. thank you for the help! 

if it is in the README then I feel bad. I'll take a look at it before I ask any more questions here.

**Comment by richyrb00** [comment]
ok so how do i sort the order of the returned data?

default i get 2,3,1...

context i've got blog posts that has a created data "created" and want to sort DESC.. 

Ideally though Contentful has in the JSON has a firstPublishedAt which would be a better option to sort by...

**Comment by alcar** [comment]
I think you should sort the entries in a separate part of your code, after fetching the posts.
To retrieve the creation date for each post, you could do something like:

```graphql
{
  posts {
    # some other data
    sys {
      createdAt
    }
  }
}
```

That's actually part of the [CDA (Content Delivery API)](https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/common-resource-attributes). There's a little mention to that in the [README section](https://github.com/contentful-labs/cf-graphql#querying) I sent you earlier:

> - a collection field accepts an optional `q` argument and resolves to a list of entities; the `q` argument is a query string you could use with the [CDA](https://www.contentful.com/developers/docs/references/content-delivery-api/)

I'm just mentioning it so you or anyone who reads this can find more information about the subject, not to make you feel bad, so don't worry! :smile:

**Comment by KevCJones** [comment]
I have thoughts about this so i'll revive this thread of conversation, i think this is related to [https://github.com/contentful-labs/cf-graphql/issues/12][https://github.com/contentful-labs/cf-graphql/issues/12], thats to say that pagination also requires collection information too.. currently the above solutions to me are about infinity scrolling friendly solutions where you can walk the results using limit and skip until the results.length < limit and you know you've reached the last batch.

However if we take a collection thats hypothetically going to be big like a collection called 'likes'. Its likely the results will outgrow the upper 'limit' of 1000 supported by contentful eventually... and  a common usecase is we'd want the TOTAL likes of a partical post/article [lets say] and we'd want a way to ask for a  collection result that contained amongst other things the `total`. 

Currently i've had to fall back to using the CDA to pull limit=1 collection queries just so i can get the total that the cf-graphql omits. 

If a dev could point me at whereabouts [if its even possible] any of the  collection data is omitted from the response, i could explore options. I'm guessing this is a deeper support thing though, that its something inside the contentful side that needs to be implemented, perhaps something like setting in the query we expect the response to be a 'collection' could be an approach?

Cheers

K

**Comment by jelz** [comment]
`skip` / `limit` arguments and metadata on collections will be a part of v0.5 release planned for the next week.

**Comment by jelz** [comment]
Released in v0.5.

Please refer https://github.com/contentful-labs/cf-graphql#querying

**Comment by KevCJones** [comment]
When i tried the new querying in v0.5.0 using skip and limit as schema params instead of query parameters my timeline output was showing that `skip` was 0 no matter what i passed through. `limit` was being respected however. 

Do you have a working demo i can compare against in case i'm doing something wrong?

**Comment by jelz** [comment]
The dev server in `dev/` directory of this repo can be used. `demo/` will be updated to use v0.5 soon. Please open a new issue with your code.
