### ISSUE TITLE
Post by url

### ISSUE THREAD

**Issue by creaux** [contentful-labs/cf-graphql#38]
Hello everyone,

I'm not sure how can I get post by url. We are of course trying to get it by meaningful url like: `this-is-post-url`. I realised that this is not quiet possible at this point. We are missing way how to handle post by custom field.

I found solution which seems to me quiet awkward and causing basically step back to REST way. Get all posts and then find by slug in collection for it's id.

Is there any other way how to do so?

**Comment by alcar** [comment]
I'm not sure this is what you're looking for, but how about something like:
```graphql
{
  tutorials (q: "fields.slug=my-post-slug") {
    # data
  }
}
```

**Comment by jelz** [comment]
@creaux the previous comment suggest a preferred way of meeting your requirement.

Does it solve your problem? What would you expect? Can you provide a GraphQL query you've mentioned in the issue description ("step back to REST").

**Comment by creaux** [comment]
Yes thanks. Closing.
