### ISSUE TITLE
locale: * and type checking

### ISSUE THREAD

**Issue by katspaugh** [contentful-labs/cf-graphql#46]
When you create a client with the locale setting set to `*`, all fields with localization enabled become objects.

This breaks the validation/coërsion of the types defined in a generated space graph. For example, if my `title` field is defined as a `String`, it will be converted to `[Object object]` with the locale set to `*`.

Any thoughts on how to make `locale: "*"` work nicely?

_Update:_ a minimal example:

My space graph:
```
  const cfSpaceGraph = {
    "id": "ribbon",
    "names": {
      "field": "ribbon",
      "collectionField": "ribbons",
      "type": "Ribbon",
      "backrefsType": "RibbonBackrefs"
    },
    "fields": [
      {
        "id": "title",
        "type": "String"
      }
    ]
  }
```
(The title field is localized)

The client:
```
const client = cfGraphql.createClient({
  spaceId,
  cdaToken,
  cmaToken,
  locale: '*'
});
```

A GraphQL query:
```
    const query = `{
      ribbons(limit: 1) {
        title
      }
    }`;

    const schema = cfGraphql.createSchema(cfSpaceGraph);

    graphql(cfSchema, query, null, {
      entryLoader: client.createEntryLoader()
    });

    // resolves with `{ "data": {"ribbons": [{ "title": "[object Object]" }] } }`
```

**Comment by GhaithZamrik** [comment]
did you find a way to make it fetch all the locale and still return a readable result?

**Comment by katspaugh** [comment]
No, we switched to one locale per request.
